// Pont minimal et sûr entre la page et le processus principal.
const { contextBridge, ipcRenderer, webUtils, webFrame } = require('electron');

contextBridge.exposeInMainWorld('ksNative', {
  openDialog: opts => ipcRenderer.invoke('open-dialog', opts),
  readFile: p => ipcRenderer.invoke('read-file', p),
  saveDialog: opts => ipcRenderer.invoke('save-dialog', opts),
  writeFile: (p, data) => ipcRenderer.invoke('write-file', p, data),
  getPending: () => ipcRenderer.invoke('get-pending'),
  recoveryWrite: (id, metadata, data) => ipcRenderer.invoke('recovery-write', id, metadata, data),
  recoveryList: () => ipcRenderer.invoke('recovery-list'),
  recoveryRead: id => ipcRenderer.invoke('recovery-read', id),
  recoveryRemove: id => ipcRenderer.invoke('recovery-remove', id),
  listFonts: () => ipcRenderer.invoke('list-fonts'),
  pathForFile: f => { try { return webUtils.getPathForFile(f); } catch { return null; } },
  confirmClose: () => ipcRenderer.send('confirm-close'),
  setTitle: t => ipcRenderer.send('set-title', t),
  setTitleBar: o => ipcRenderer.send('set-titlebar', o),
  toggleDevTools: () => ipcRenderer.send('toggle-devtools'),
  toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
  showInFolder: p => ipcRenderer.send('show-in-folder', p),
  onOpenPath: fn => ipcRenderer.on('open-path', (_e, p) => fn(p)),
  onCloseRequest: fn => ipcRenderer.on('close-request', () => fn()),
  aiStatus: () => ipcRenderer.invoke('ai-status'),
  aiDownload: id => ipcRenderer.invoke('ai-download', id),
  aiSegment: (id, input) => ipcRenderer.invoke('ai-segment', id, input),
  onAiProgress: fn => ipcRenderer.on('ai-progress', (_e, p) => fn(p)),
  appVersion: () => ipcRenderer.invoke('app-version'),
  updateState: () => ipcRenderer.invoke('update-state'),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  updateDownload: () => ipcRenderer.invoke('update-download'),
  updateInstall: () => ipcRenderer.send('update-install'),
  onUpdateStatus: fn => ipcRenderer.on('update-status', (_e, s) => fn(s)),
  setZoom: f => webFrame.setZoomFactor(f),
});
